name: Rust CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Cargo Fmt, Check, and Clippy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Cargo Fmt
        run: cargo fmt --all -- --check

      - name: Cargo Check (all features)
        run: cargo check --all --all-features

      - name: Cargo Clippy (all features)
        run: cargo clippy --all --all-features -- -D warnings